### ISSUE TITLE
ModuleNotFoundError: No module named 'posix' and ModuleNotFoundError: No module named 'scandir'

### ISSUE THREAD

**Issue by Coderx7** [andhus/dirhash-python#3]
Hi, 
I'm having issues running dirhash in python3.7. upon trying  to hash a directory, I get this error message: 
```python
Traceback (most recent call last):
  File "C:\Users\User\Anaconda3\Lib\site-packages\scantree\compat.py", line 20, in <module>
    from posix import DirEntry
ModuleNotFoundError: No module named 'posix'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\Codes\ols\python\test_beds\testbed_stuff.py", line 12, in <module>
    from dirhash import dirhash
  File "C:\Users\User\Anaconda3\Lib\site-packages\dirhash\__init__.py", line 13, in <module>
    from scantree import (
  File "C:\Users\User\Anaconda3\Lib\site-packages\scantree\__init__.py", line 3, in <module>
    from ._path import (
  File "C:\Users\User\Anaconda3\Lib\site-packages\scantree\_path.py", line 7, in <module>
    from .compat import (
  File "C:\Users\User\Anaconda3\Lib\site-packages\scantree\compat.py", line 22, in <module>
    from scandir import scandir as _scandir
ModuleNotFoundError: No module named 'scandir'
```
Is this compatible with windows10? 
Whats the issue here?

**Comment by nikolarobottesla** [comment]
@Coderx7 , I just had to manually install scandir using pip on windows 10
